name: Simple VoltAgent Diagnostic
on:
  workflow_dispatch:

jobs:
  diagnose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Check current state
        run: |
          echo "=== REPOSITORY STATUS ==="
          echo "Current repository: ${{ github.repository }}"
          echo "Default branch: ${{ github.event.repository.default_branch }}"
          
          echo "=== CURRENT REMOTES ==="
          git remote -v
          
          echo "=== CURRENT BRANCHES ==="
          git branch -a
          
          echo "=== TEST UPSTREAM ACCESS ==="
          echo "Testing old upstream (PawanOsman)..."
          git ls-remote https://github.com/PawanOsman/voltagent.git HEAD || echo "❌ Old upstream not accessible"
          
          echo "Testing new upstream (VoltAgent)..."
          git ls-remote https://github.com/VoltAgent/voltagent.git HEAD || echo "❌ New upstream not accessible"
          
          echo "=== FORK INFORMATION ==="
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}" | \
            jq '.fork, .parent.full_name, .parent.clone_url'
